server:
  port: 8083

# nacos 配置中心
nacos:
  discovery:
    server-addr: slave4:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: myspace-api
    version: 1.0.0
#    parameters:
#      unicast: false
  registry:
#    address: N/A
#    address: #multicast://224.5.6.7:1234
#    address: zookeeper://127.0.0.1:2181
    address: nacos://slave4:8848
  protocol:
    name: dubbo
    port: -1

# Swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  # 请求前缀
#  pathMapping: /api

# 防止XSS攻击
#xss:
#  # 过滤开关
#  enabled: false
#  # 排除链接（多个用逗号分隔）
#  excludes: /system/notice/*
#  # 匹配链接
#  urlPatterns: /system/*,/monitor/*,/tool/*,/vacation/*

# Springfox 使用的路径匹配是基于AntPathMatcher的，而 Spring Boot 2.6.X使用的是 PathPatternMatcher。
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER